plugins {
    id 'java'
    id 'net.serenity-bdd.serenity-gradle-plugin' version "${serenityGradleVersion}"
}

subprojects {
    apply plugin: 'java'
    group = 'com.reto.automation'
    version = '1.0'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    repositories {
        mavenCentral()
    }

    compileJava.options.encoding = 'UTF-8'
    compileTestJava.options.encoding = 'UTF-8'

    tasks.withType(Test).configureEach {
        defaultCharacterEncoding = 'UTF-8'
    }

    dependencies {
        implementation "net.serenity-bdd:serenity-core:${serenityCoreVersion}"
        implementation "net.serenity-bdd:serenity-cucumber:${serenityCoreVersion}"
        implementation "net.serenity-bdd:serenity-playwright:${serenityCoreVersion}"
        testImplementation "net.serenity-bdd:serenity-junit5:${serenityCoreVersion}"
        testImplementation "net.serenity-bdd:serenity-ensure:${serenityCoreVersion}"
        testImplementation "org.junit.jupiter:junit-jupiter:5.10.2"
        testImplementation "org.junit.vintage:junit-vintage-engine:5.10.2"
        testImplementation "org.junit.platform:junit-platform-suite-api:1.10.2"
        testImplementation "org.junit.platform:junit-platform-suite-engine:1.10.2"
        testImplementation "io.cucumber:cucumber-junit-platform-engine:7.34.2"
        testImplementation "org.assertj:assertj-core:${assertJVersion}"
        compileOnly "org.projectlombok:lombok:${lombokVersion}"
        annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
        testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
        testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    }

    test {
        useJUnitPlatform()
    }
}
